### ISSUE TITLE
Consider rearranging the time to the top center and following R6's hud

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#101]
This is up in the air and might not happen.

- I'm not a fan of the black gradients I'm using at the bottom.
- I liked the time counter at the top
- I think the font size should be reduced a few pixels

**Comment by michaeljcalkins** [comment]
![r6-dust-line-feature-loadout_248350](https://cloud.githubusercontent.com/assets/8272012/19376159/2bd6515c-9190-11e6-8e2d-745a27d7b684.jpg)
![rainbow-six-siege-3-1280x677](https://cloud.githubusercontent.com/assets/8272012/19376160/2de2e082-9190-11e6-82d4-112b806611db.jpg)
![rainbow_six_siege_2](https://cloud.githubusercontent.com/assets/8272012/19376162/2fbc909c-9190-11e6-83f9-1e172f499ff0.jpg)

**Comment by michaeljcalkins** [comment]
![rainbow-six](https://cloud.githubusercontent.com/assets/8272012/19376210/92d6c81e-9190-11e6-9b98-d1e58f78b2ce.png)

**Comment by michaeljcalkins** [comment]
I'm not happy with the position of the clock being at the bottom with the gradient like it is.
Maybe it's just me but I'd like it up top and center.  I feel like it's more important that way.  

We could also use this position for game mode scores someday.

**Comment by And-re** [comment]
Yeah, I agree. For Team matches we need to display scores and top center position seems better.

**Comment by michaeljcalkins** [comment]
@daniphilia This one is super easy.

**Comment by michaeljcalkins** [comment]
![bf1-2016-07-16-13-30-00-71](https://cloud.githubusercontent.com/assets/8272012/19582771/1a924e12-96ec-11e6-8ebe-afaf0d7d2b33.jpg)
