### ISSUE TITLE
Add stationary rogue AI Turrets

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#105]
![screen_shot_2016-10-15_at_10_47_41_pm](https://cloud.githubusercontent.com/assets/8272012/19453618/df4d3f84-946a-11e6-9836-f25d4a480c53.png)

**Comment by michaeljcalkins** [comment]
![screen shot 2016-10-17 at 1 12 38 pm](https://cloud.githubusercontent.com/assets/8272012/19453757/6d04b262-946b-11e6-8875-b29f493f318c.png)
![screen shot 2016-10-17 at 1 12 46 pm](https://cloud.githubusercontent.com/assets/8272012/19453761/6f1a431e-946b-11e6-8a43-e51738c2ea89.png)

**Comment by michaeljcalkins** [comment]
Code that makes this work is here:
https://github.com/michaeljcalkins/rangersteve/tree/feature/bots

**Comment by michaeljcalkins** [comment]
The main idea behind this is that it will help Ranger Steve keep players engaged when there are not a lot of other players online. 

In diep.io every time an enemy of this type appears the players flock to it to fight because of the amount of score you get from killing it.

**Comment by michaeljcalkins** [comment]
I'm voting yes for Post-Release

**Comment by michaeljcalkins** [comment]
I think the first iteration should just be rogue turrets that shoot at everyone and then we can iterate on that.

**Comment by And-re** [comment]
I think AI turrets are easier to implement than bots moving around the map.
And I agree that they may keep players engaged if there are not many players in the room.

**Comment by B-r-u-c-e** [comment]
would the turret go away if, say 5 or people were on a server? If it isn't its own game mode, I can see it making a lot of people mad who don't want to fight the bot. Maybe if the map was bigger, or the bot had an isolated area on the map, then players could basically choose to fight the bot or others.

**Comment by And-re** [comment]
@B-r-u-c-e the idea was to add the AI Turrets so that you have something to do when there are only a few (1-3) players in the room.
We will consider any suggestions.

**Comment by B-r-u-c-e** [comment]
Okay, 1-3 makers sense. Maybe consider a team AI turret for TDM when 1 team has more players than the other as well.

**Comment by michaeljcalkins** [comment]
@B-r-u-c-e And-re is exactly right and then someday create a "domination" game mode where you try to take control of 2 - 4 turrets to win.
