### ISSUE TITLE
IDEA: Buying guns using your score

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#107]
- Everyone starts out with 0 score, when you switch guns it costs you your score
- AK is free
- When you kill AI Turret or enemy you'll gain score that you can use to buy guns

**Comment by michaeljcalkins** [comment]
Beta Milestone
Fairly easy to implement, when a user changes their weapon subtract it's cost from their score.

Example games: 
- Counter Strike Source
- GTA

**Comment by michaeljcalkins** [comment]
This might require playtesting to really know if this is any good.

**Comment by michaeljcalkins** [comment]
@And-re The more I think about this the less I like it.

**Comment by And-re** [comment]
@michaeljcalkins I think that in CS:GO you get more money (could be score in our case) if you kill someone with a worse weapon

**Comment by michaeljcalkins** [comment]
I'd like to reject this for now.
