### ISSUE TITLE
At the end of the round have users vote on the next map

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#110]

**Comment by michaeljcalkins** [comment]
Beta Milestone

**Comment by michaeljcalkins** [comment]
@And-re @daniphilia What do you guys think?
I'm in favor of this, I loved this in Call of Duty.  I literally watched my brother cringe or get happy depending on what people voted on.

**Comment by And-re** [comment]
I like that idea (that's why I suggested it)

**Comment by michaeljcalkins** [comment]
Lol I'm just going to move this to approved.
