### ISSUE TITLE
Phaser is intercepting  MacOS "COMMAND" key -- have to click out of game view (omnibar) to use window key bindings

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#112]

**Comment by michaeljcalkins** [comment]
I'm thinking it would be good to just attach CMD+R to a `document.location.reload()` or something.

**Comment by michaeljcalkins** [comment]
Honestly I'm not really worried about this, I'd prefer to keep energy on other things.

**Comment by And-re** [comment]
And the issue isn't valid. The game is intercepting keys that are mapped in the Controls settings.
