### ISSUE TITLE
IDEA: small opaque indicator on bottom-right corner/mid-right that displays where on map enemies are with small dots

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#113]

**Comment by michaeljcalkins** [comment]
I've thought about this for a long time and I like the idea of it.  Would need to come after the alpha release though.

All the information you need to make is accessible in the `state.room.players` var in Redux.

**Comment by And-re** [comment]
I don't agree with that idea. You will lose the possibility to surprise your enemies.
It can be used for showing teammates in other modes like team deathmatch or ctf though.

**Comment by michaeljcalkins** [comment]
I'm going to have to agree with Andre, part of this game has to be surprise attacks.
