### ISSUE TITLE
Player's spawn point needs to be decided on the server when they join and on respawn

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#114]

**Comment by michaeljcalkins** [comment]
GameConsts.js will likely need to be converted from ES6 to a CommonJS module for NodeJS.

**Comment by And-re** [comment]
we can use ES2015+ in node.js as well

**Comment by michaeljcalkins** [comment]
@And-re Out of curiosity is there actually anything bad happening here if they do pull a spawn point from the map files?

**Comment by michaeljcalkins** [comment]
This is a fairly simple conversion but I'm not sure there's any value here if we're not validating player movements at the moment.

**Comment by And-re** [comment]
@michaeljcalkins If you want to prevent cheating and be sure that the next spawn point election algorithm works correctly it needs to be decided on the server

**Comment by michaeljcalkins** [comment]
Ok nvm lets do it.

**Comment by michaeljcalkins** [comment]
@And-re I was going to convert maps to CommonJS so that the server can use the same file.

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/373
