### ISSUE TITLE
Use yarn instead of npm on heroku

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#117]
https://medium.com/@ekryski/using-yarn-with-circleci-and-heroku-31d0d247bd59#.7ldji9ylx

Step 3

**Comment by michaeljcalkins** [comment]
![cursor_and_rangersteve_ _build___heroku_](https://cloud.githubusercontent.com/assets/8272012/19649721/b72b4432-99bb-11e6-9de4-8d97de34c10f.png)

**Comment by And-re** [comment]
@michaeljcalkins maybe you will have more motivation to do it faster :P

**Comment by And-re** [comment]
@michaeljcalkins I think this is done
