### ISSUE TITLE
IDEA: quick chat commands like in Wolfenstein: Enemy Territory

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#120]
https://eurotoxic.wordpress.com/2009/10/06/wolfenstein-enemy-territory-quick-chats/
http://static.giantbomb.com/uploads/original/1/13824/409788-f8dd24b873b34a00c7dbffbe90e888bc87a2a543.jpg
for example you press v56 to say Great shot or v55 to say Good Game

**Comment by michaeljcalkins** [comment]
This is also in Left 4 Dead.
We man need to play test this or ask for some opinions.  
I know I type a "quick chat message" when I die :P
I'm thinking Post-Release

**Comment by And-re** [comment]
Yes it can be added in Post-Release, it's not that important right now.
