### ISSUE TITLE
Create a room's list button on the homepage that shows all active rooms with corresponding maps, gamemodes, and current players

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#124]
![](https://cloud.githubusercontent.com/assets/328414/19694551/207006a6-9ae0-11e6-85d9-e8255360ced7.png)

**Comment by michaeljcalkins** [comment]
Conflicts with #110

**Comment by michaeljcalkins** [comment]
![](https://cloud.githubusercontent.com/assets/8272012/19421448/62df960e-93b6-11e6-9c86-ff924269e3fb.png)

**Comment by michaeljcalkins** [comment]
Honestly I don't want this.  I really enjoy in Airsoft how the all the games we play are fun and change every round.  That's why I haven't made a room system for RangerSteve I want people to jump in and just start playing.

I also value the map selector more than this.

**Comment by And-re** [comment]
So I guess we should add a way to choose a game mode on the start page (with Deathmatch as default)

**Comment by michaeljcalkins** [comment]
I was thinking someday we could list all the rooms with their current game modes and let them pick what room to go in.

**Comment by michaeljcalkins** [comment]
I think to keep the game fresh each room just randomly rotates through gamemodes so you're never playing the same thing.

**Comment by michaeljcalkins** [comment]
![diep_io](https://cloud.githubusercontent.com/assets/8272012/19694548/ad525462-9a94-11e6-9c77-ae0296d1711e.png)

This segments the audience greatly because their rounds never end in some gamemodes.

**Comment by And-re** [comment]
Yeah, something like this:
![screen shot 2016-10-25 at 18 23 07](https://cloud.githubusercontent.com/assets/328414/19694551/207006a6-9ae0-11e6-85d9-e8255360ced7.png)

**Comment by And-re** [comment]
In Overwatch the modes change all the time.

**Comment by michaeljcalkins** [comment]
Love that, once we release it'd be easy to add a "rooms" button to let the player jump in on what they want.
