### ISSUE TITLE
Leaderboard updates!

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#128]
Identify who's first second or third with a number next to their name (not leaderboard actually in game)

- [x] https://github.com/michaeljcalkins/rangersteve-ideas/issues/14
- [x] Add #1 #2 or #3 to the top three player's names in game #1 And_re
- [x] Add numbers to all rows in leaderboard modal
- [ ] Widen leaderboard modal (hopefully allowing us to add more stats in the future)

**Comment by michaeljcalkins** [comment]
![rangersteve_io](https://cloud.githubusercontent.com/assets/8272012/19694011/881b6af0-9a92-11e6-96d8-3556a4fa53ea.png)

**Comment by michaeljcalkins** [comment]
I'd have to play test this but I have a feeling it'd be great.

**Comment by And-re** [comment]
I think someone wanted that also here (new column on the left)
![screen shot 2016-10-25 at 18 09 08](https://cloud.githubusercontent.com/assets/328414/19694089/3c4f52d4-9ade-11e6-8ad6-1e498c092703.png)

**Comment by michaeljcalkins** [comment]
@And-re You think just for the first three rows or number the whole thing.  I like this idea.

**Comment by And-re** [comment]
For the whole thing.
And I think we should use a wider modal for the Leaderboard (the same as for Controls and Weapons)

**Comment by michaeljcalkins** [comment]
1. Add #1 #2 or #3 to the top three player's names in game
2. Add numbers to all rows in leaderboard modal
3. Widen leaderboard modal (hopefully allowing us to add more stats in the future)

**Comment by michaeljcalkins** [comment]
Calling this good for now we can widen the leaderboard later when we need to add something.
