### ISSUE TITLE
Be able to remap jump jet flying to a something other than mouse right click.

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#130]

**Comment by michaeljcalkins** [comment]
People who play on touchpads are the main proponents behind this feature.
Would this be helpful for tablets/mobile too?

**Comment by michaeljcalkins** [comment]
I'm gonna vote no for now.

**Comment by And-re** [comment]
I think the problem for people using touchpads is that you can't remap the fly action key.
So I think we should allow remapping that key and it's quite easy to do.

**Comment by michaeljcalkins** [comment]
Omg d'oh! 
We'll need an if statement in there because left & right click don't coincide with the Phaser keyboard stuff.
