### ISSUE TITLE
IDEA: Once fuel gauge is empty, holding down right click shouldn't continue draining

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#133]
Should reset so player has to right click and hold again.

**Comment by michaeljcalkins** [comment]
There's actually a really weird floating effect that takes place, so I'm all for this.

**Comment by michaeljcalkins** [comment]
In the interest of saving time I think we should wait until people complain about this.  The weird floating gives you no advantages in game play and makes you an easy target.
