### ISSUE TITLE
UX: Respawn countdown off by 25 seconds, Endgame countdown off too

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#134]
It's true.

**Comment by michaeljcalkins** [comment]
@daniphilia can you throw in a screenshot if you see it? I have had a few people tell me about this but I have no idea.

**Comment by daniphilia** [comment]
I get it every time.

**Comment by daniphilia** [comment]
![screen shot 2016-10-26 at 10 56 33 pm](https://cloud.githubusercontent.com/assets/19393511/19755906/0eec56b6-9be7-11e6-892c-15a52edf2f95.png)

**Comment by michaeljcalkins** [comment]
@daniphilia I have no idea how to replicate this and I think your computer is the only one doing this.  If you can figure out what's going on I can help with a fix.
