### ISSUE TITLE
UX: Rocket boot sound loop

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#135]
I think it happens when the match ends and you're flying, or you are flying and then switch tabs and then come back after a while.

**Comment by michaeljcalkins** [comment]
Do you mean the jump jet sound gets stuck in a loop continuously playing?

**Comment by daniphilia** [comment]
Yes.

**Comment by michaeljcalkins** [comment]
Likely solution: When the round is over and we pause the game the jumpjet needs to have it's audio stopped.

**Comment by michaeljcalkins** [comment]
When the round ends stop all sound effects and reset inputs.

**Comment by michaeljcalkins** [comment]
Should not happen anymore at the end of the round.
