### ISSUE TITLE
Show current killing spree for each user on the leaderboard when greater than one

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#14]

**Comment by michaeljcalkins** [comment]
When players get kill streaks trigger strike packages:

WE WILL NOT FEAR THE RED MENACE
red lighting explodes somewhere on the map

WARNING: ORBITAL STRIKE IMMINENT
drop bombs from above

SCANNING FOR ENEMIES; FORCIBLE IMPACT ALERT
an orbital laser fires from above  and moves on the map killing anyone it touches

ENGAGING ENEMY INFANTRY
helicopter style chain gun attack

ENERGY DRIVE IS ONLINE; WARNING ENGAGING ENEMIES
laser blaster attack

https://www.youtube.com/watch?v=NNHCebtN3e4

**Comment by michaeljcalkins** [comment]
I imagine this saying something like:

![screen_shot_2016-10-15_at_1_45_56_pm](https://cloud.githubusercontent.com/assets/8272012/19570778/422e8166-96b0-11e6-8016-ebfa52b3f4f8.png)

**Comment by And-re** [comment]
@michaeljcalkins and I can make your imagination come true if you implement it

**Comment by michaeljcalkins** [comment]
I've played with several people who have typed in chat "ULTRA KILL" "TRIPLE KILL".

**Comment by And-re** [comment]
oh, you just reminded me about quick chat commands like in Wolfenstein:Enemy Territory
https://eurotoxic.wordpress.com/2009/10/06/wolfenstein-enemy-territory-quick-chats/
http://static.giantbomb.com/uploads/original/1/13824/409788-f8dd24b873b34a00c7dbffbe90e888bc87a2a543.jpg
for example you press v56 to say Great shot or v55 to say Good Game

**Comment by michaeljcalkins** [comment]
I would like to know when you're on a kill streak, but I feel like there's a better way to do this.

**Comment by And-re** [comment]
maybe we can use the kill log for that

**Comment by michaeljcalkins** [comment]
![rangersteve_io_](https://cloud.githubusercontent.com/assets/8272012/19693784/9f15d3a4-9a91-11e6-8750-c06584fda6ff.png)

We could put people's current kill streak if greater than one on the leaderboard.  That'd be pretty sweet.

**Comment by michaeljcalkins** [comment]
When you die that would go back to 0.

**Comment by And-re** [comment]
Yeah, the use of the leaderboard is a good idea

**Comment by michaeljcalkins** [comment]
If we do it this way I would LOVE to see this.

**Comment by michaeljcalkins** [comment]
Is now a part of the other leaderboard task.
