### ISSUE TITLE
Restart rooms when the round ends, not when the next round counter reaches 0

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#145]
![screen_shot_2016-11-02_at_20 44 09](https://cloud.githubusercontent.com/assets/8272012/19944752/51863ca4-a0fa-11e6-921d-030ae689a961.png)

https://github.com/michaeljcalkins/rangersteve/blob/master/app/sockets.js#L51

to 

https://github.com/michaeljcalkins/rangersteve/blob/master/app/sockets.js#L89

Potentially delete this logic:
https://github.com/michaeljcalkins/rangersteve/blob/master/app/sockets.js#L369

**Comment by michaeljcalkins** [comment]
@And-re This snippet has been deleted, I want to see if this fixes the issue.

```
    // Remove empty rooms
    const emptyRoomIds = Object.keys(rooms)
        .filter(roomId => Object.keys(rooms[roomId].players).length === 0)
    util.log('Deleting rooms: ', emptyRoomIds)
    emptyRoomIds.forEach(roomId => delete rooms[roomId])
```

**Comment by And-re** [comment]
@michaeljcalkins so you haven't tested the code without this snippet locally?

**Comment by michaeljcalkins** [comment]
@And-re I was running it locally with short round times and it works fine.  Idk some of these bugs don't show until tons of players are on it.

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/255

**Comment by michaeljcalkins** [comment]
Closing for now appears to be working.  Reopen if wrong.
