### ISSUE TITLE
Gamemode - Ultra rocket fire || Shotgun mode

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#150]
Rockets reload 300% faster, start with 4 rockets

shotgun only mode

Can mix with team deathmatch or deathmatch modes too.

Algorithm that augments deathmatch/team deathmatch at some % chance

**Comment by michaeljcalkins** [comment]
Don't forget **sniper only mode**!

**Comment by michaeljcalkins** [comment]
https://rangersteve.userecho.com/topics/20-/
