### ISSUE TITLE
Reloading needs to stop when you switch weapons to prevent instant reloads

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#154]
http://imgur.com/a/NWq8m

**Comment by michaeljcalkins** [comment]
There have been a couple times I instantly get a second shot with the RPG.

**Comment by michaeljcalkins** [comment]
Example: http://i.imgur.com/IEWCGk2.gif

Using the Barrett and Desert Eagle
My ammo count for both guns goes down

Push Q and left click alternating quickly before the reload can start.

**Comment by michaeljcalkins** [comment]
@And-re This was used against me hard last night. Deagle > Barrett > Deagle > Barrett > Deagle > Barrett > Deagle > Barrett > Deagle > Barrett

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/357
