### ISSUE TITLE
Stop the virtual dom from updating every frame

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#157]

**Comment by michaeljcalkins** [comment]
There is a deeper issue here that inferno will not resolve.  
RS currently re renders the virtual dom every frame.

**Comment by michaeljcalkins** [comment]
http://stackoverflow.com/a/24719289/1069899

**Comment by And-re** [comment]
@michaeljcalkins maybe we should use mapStateToProps in most component and just use fields from the state that are really needed?

**Comment by michaeljcalkins** [comment]
@And-re I completely agree.

**Comment by michaeljcalkins** [comment]
@And-re Isn't this done?

**Comment by And-re** [comment]
@michaeljcalkins No, I tried using "mapStateToProps" but that's not good enough

**Comment by michaeljcalkins** [comment]
This might work
https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate

**Comment by And-re** [comment]
@michaeljcalkins Another problem is that the changes in our Redux store are triggered 20 times per second and that causes our main component GameUi to rerender every time and the same with all its children. I think that using shouldComponentUpdate on all (or most) components 20 times per second is just wasteful.

**Comment by michaeljcalkins** [comment]
@And-re It looks like you could do some sort of shallow compare on select state objects at the top level.
https://www.reddit.com/r/reactjs/comments/4lf3dz/should_i_use_shouldcomponentupdate/

**Comment by And-re** [comment]
They recommend using React.PureComponent instead https://facebook.github.io/react/docs/shallow-compare.html
That's what I used some time ago but for some components using PureComponents wasn't working correctly.

**Comment by michaeljcalkins** [comment]
@And-re This doesn't appear to be adversely effecting performance.  Worth investigating?

**Comment by And-re** [comment]
I think improving that would require a massive refactor of our UI components and to rethink our redux store as well.
Because right now we are changing the redux store 50 times per second.
We can put it on hold but I think this might be effecting performance on slower machines.
