### ISSUE TITLE
Sometimes you don't see any players when you join a room

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#160]
Even though you see their names on the player list and you have to refresh the game to actually see them

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve-ideas/issues/187

**Comment by michaeljcalkins** [comment]
https://youtu.be/imT36cLPNqw

**Comment by michaeljcalkins** [comment]
Wimpzer : I have no idea, as I just clicked spawn .. However this is the second time while you been streaming today
Wimpzer : Update: After waiting I begin to see some people, however some are still invisible
Wimpzer : As far as I understand everyone is invisible at the start of the map, but I can see them when they reconnect (I believe they reconnect)
Wimpzer : However it seems like they can't see me (They're not shooting at me)
Wimpzer : But if I'm in their range of fire I die

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/329
