### ISSUE TITLE
Player doesn't respawn and no respawn modal appears

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#161]
bug by Savage
"I was down on the left side with 10hp, i got killed of course. but instead of the respawn menu, i fley up to the upper part of the map (could not control it) weapons were working, i could hear jump sounds and fly sounds even weapon fire sounds. but my hp kept @ 10hp until match was over"

![](https://cdn.discordapp.com/attachments/258259797046984704/258259898461061130/New_bug.png)

**Comment by michaeljcalkins** [comment]
Holy shit!

**Comment by And-re** [comment]
I'm wondering if it has something to do with that x, y position bug from yesterday

**Comment by michaeljcalkins** [comment]
![rangersteve_io_](https://cloud.githubusercontent.com/assets/8272012/21292269/b8bdc3f6-c4b3-11e6-9384-b6dc06c1df19.png)

I don't think this is related to our newest updates because it happened before we updated.  Happened to me and have no idea how to reproduce it.

**Comment by michaeljcalkins** [comment]
I still don't know how to reproduce this bug :/

**Comment by michaeljcalkins** [comment]
I bet you there is an issue where a player's health is never updated while they are actually dead.

**Comment by michaeljcalkins** [comment]
I managed to reproduce that bug with low health and no respawn after death
![screen_shot_2017-01-12_at_23 39 44](https://cloud.githubusercontent.com/assets/8272012/21915515/2d7c57a8-d8ef-11e6-81b7-ce06682bd5e2.png)

**Comment by michaeljcalkins** [comment]
The respawn modal showed for a second and then it disappeared and i was just stuck dead.
Was still shooting but couldn't see myself.
![screen shot 2017-01-15 at 2 49 26 pm](https://cloud.githubusercontent.com/assets/8272012/21966937/0536b546-db32-11e6-9cf7-dd467c72d3d2.png)

**Comment by michaeljcalkins** [comment]
If I kill myself again this is fixed.

**Comment by And-re** [comment]
It's still happening

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/445

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/449
