### ISSUE TITLE
Cannot read property of getFirstDead of undefined

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#163]
![unknown 1](https://cloud.githubusercontent.com/assets/8272012/21154133/19278910-c122-11e6-9da5-ff54b1c195fc.png)

Found by @itsshady101

**Comment by michaeljcalkins** [comment]
I have no idea what causes this but it happens periodically.

**Comment by And-re** [comment]
does it really still happen?

**Comment by michaeljcalkins** [comment]
Yeah but I need to upload my screenshot.  It might be from a different var

**Comment by michaeljcalkins** [comment]
Yesterday it happened

**Comment by itsshady101** [comment]
![image](https://cloud.githubusercontent.com/assets/15066223/21740539/6f84c966-d4e2-11e6-8791-b6ed5208f6d2.png)

**Comment by itsshady101** [comment]
Hmm :/
