### ISSUE TITLE
Stats need to be checked for bugs

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#174]
![screen shot 2016-12-29 at 11 02 42 am](https://cloud.githubusercontent.com/assets/8272012/21552469/94620bdc-cdb6-11e6-9189-280d8607ea6a.png)

Specifically accuracy

**Comment by And-re** [comment]
Best Kills per minute is wrong
![screen_shot_2016-12-30_at_14 39 38](https://cloud.githubusercontent.com/assets/328414/21595187/614f5bdc-d12b-11e6-9ac9-1d5ef5ef28e3.png)

**Comment by And-re** [comment]
![screen_shot_2017-01-02_at_12 14 55](https://cloud.githubusercontent.com/assets/328414/21595190/786ef3cc-d12b-11e6-98c1-738af183de6d.png)

**Comment by michaeljcalkins** [comment]
And that one player has blank score rows
