### ISSUE TITLE
Respawn is broken and players respawn instantly

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#175]

**Comment by michaeljcalkins** [comment]
https://gyazo.com/499c9bde746b3897adbbcbaaaf096981

**Comment by michaeljcalkins** [comment]
I have no idea how to reproduce this bug.

**Comment by michaeljcalkins** [comment]
It is not client side timestamp related, so I need to go through the whole respawn process.

**Comment by michaeljcalkins** [comment]
https://gyazo.com/0a4bbaec9b0893f46b507d93162753ab

**Comment by And-re** [comment]
A way to reproduce this:
1. In Data & Time uncheck set date and time automatically
2. Move your time forward
3. Save the changes
4. Restart browser
![screen shot 2017-01-12 at 18 14 25](https://cloud.githubusercontent.com/assets/328414/21900120/f4bb4b28-d8f2-11e6-98dd-23bed9e95573.png)
