### ISSUE TITLE
Change quality to downscale game while zooming out camera

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#176]
GuineaGuy99 : the only solutions are too stop scaling if the aspect ratio gets too crazy or to just straight up letterbox

you can downscale game but you need to scale camera out to compensate

**Comment by michaeljcalkins** [comment]
http://jsfiddle.net/lewster32/NMNJ7/
http://www.html5gamedevs.com/topic/7150-how-to-zoom-out-from-center-of-gameworld/

**Comment by michaeljcalkins** [comment]
@And-re Do you think this is actually a thing we could do?  It seems to use the same scaling we are using.

**Comment by And-re** [comment]
@michaeljcalkins it seems similar to this.game.scale.setGameSize(widthScaleFactor, heightScaleFactor) but maybe it can help somehow in our case

**Comment by michaeljcalkins** [comment]
We will explore other solutions in the meantime.
