### ISSUE TITLE
Jumping and jetpack allow for much greater height

### ISSUE THREAD

**Issue by DrEvilGenius** [michaeljcalkins/rangersteve-ideas#177]
https://gyazo.com/18e4c8dcbe29c64f9536e32b9f50c4d8

Saves a ton of jetpack fuel/energy/power. So, not sure if you want that as a mechanic because the time isnt super super easy, or if thats abusing the jetpack fuel balance. Will leave for you to decide but yeah <3

**Comment by michaeljcalkins** [comment]
Expected behavior but thanks!
