### ISSUE TITLE
We need some sort of delta time controlling player movement

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#180]
Its kinda hard to see in the video, but can you see how it randomly speeds up sometimes (note when I'm going up on the left side and later when I'm falling on the right), also you can clearly see my fps exceeding 60 on the bottom right of the screen. https://drive.google.com/file/d/0Bx6AZXjNWLAJNzJ5WGJnQTBXcXM/view?usp=sharing

ok maybe not "clearly", its a little blurry, but hopefully you can make it out

------

Right now players are not moving at the same speed or can move faster than anyone else.  Maximum movement per second would be helpful here.

**Comment by michaeljcalkins** [comment]
GuineaGuy99 : although the solution is not to add a limit to maximum speed, that wont fix the issue
GuineaGuy99 : the idea is you should be getting the difference of time between frames and then multiplying that with your players velocity before adding it onto the position of the player, eg deltaTime, that way faster computers will move at the same speed and slower computers will also move at the same speed
GuineaGuy99 : player.x += velocity.x * deltaTime;

**Comment by michaeljcalkins** [comment]
http://www.html5gamedevs.com/topic/10345-phaser-220-release-candidate-11-please-test/

**Comment by And-re** [comment]
@michaeljcalkins but we still have to do something to fix this

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/332
