### ISSUE TITLE
IDEA: Button to refresh servers for your region

### ISSUE THREAD

**Issue by DrEvilGenius** [michaeljcalkins/rangersteve-ideas#182]
Maybe just the typical refresh arrow icon printed ontop of the region itself? Seeing as reclicking it refreshes it people will just click it

https://gyazo.com/84882305ed4f84adf53dd4b976c66124

**Comment by And-re** [comment]
I would add it next to Rooms (x)

**Comment by DrEvilGenius** [comment]
Ah okay, that makes sense, I just put it there because clicking the region refreshes it already, so adding an image would make people think its a button and technically it would refresh still. Just less effort for same thing. But if easy or want to add it next to rooms then its probs better yeah

**Comment by michaeljcalkins** [comment]
https://rangersteve.userecho.com/topics/7-/
