### ISSUE TITLE
Can walk on the bottom of HighRuleJungle when window is resized to extreme ratio's

### ISSUE THREAD

**Issue by GuineaGuy99** [michaeljcalkins/rangersteve-ideas#184]
Video: https://drive.google.com/file/d/0Bx6AZXjNWLAJVGhsWVd0bHlqMjQ/view?usp=sharing

Its worth noting that it only works on the right side of the map, if you walk too far to the left you will die, and if you resize at any point you will also die.

User "savage" suggested that it may be happening due to the map being repeated.

**Comment by And-re** [comment]
@GuineaGuy99 Congratulations! You found the easter egg prepared by @michaeljcalkins

**Comment by michaeljcalkins** [comment]
This is presumably fixed but will need testing after being deployed.

**Comment by And-re** [comment]
I checked it locally and it seems fixed
