### ISSUE TITLE
Can't get past the loading screen

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#189]
![screen shot 2017-01-08 at 1 09 45 pm](https://cloud.githubusercontent.com/assets/8272012/21753525/d64785d2-d5a3-11e6-9298-29d600be0f74.png)

Have to refresh until I can get in.

**Comment by michaeljcalkins** [comment]
I have no idea how to reproduce this bug.

**Comment by And-re** [comment]
@michaeljcalkins I know how to reproduce this bug. Just change focus to a different app when it starts loading.

**Comment by michaeljcalkins** [comment]
@And-re I think I was just changing focus to another Chrome window.

**Comment by And-re** [comment]
That's enough to trigger the bug

**Comment by And-re** [comment]
I think it has something to do with the tab visibility change event

**Comment by michaeljcalkins** [comment]
@And-re Re assign me to this if you want me to take over.  I was having a hard time reproducing it even when I lost focus on the tab.

**Comment by And-re** [comment]
it's very easy to reproduce:
1. use half of you screen
2. refresh or use the Play Now button
3. quickly click on the desktop
