### ISSUE TITLE
getFirstDead of undefined is still happening

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#191]
![screen shot 2017-01-09 at 12 46 25 pm](https://cloud.githubusercontent.com/assets/8272012/21782877/d81f33b6-d669-11e6-8381-5b79ccebf5e4.png)

**Comment by michaeljcalkins** [comment]
Note, the last error is a chrome extension error.

**Comment by And-re** [comment]
@michaeljcalkins Do you know how to reproduce this? I think I have never had that error

**Comment by michaeljcalkins** [comment]
@And-re The only time this has happened is when there is a sudden performance drop.  I cannot reproduce this though.

**Comment by And-re** [comment]
@michaeljcalkins what about getFirstExists? and maybe we should have more objects allocated for enemy bullets rather than our bullets.
Right now we have 300 bullets for our player and 200 bullets for other players.
