### ISSUE TITLE
When you press t to chat your nickname get's inserted into the input field

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#192]
![screen shot 2017-01-09 at 12 40 44 pm](https://cloud.githubusercontent.com/assets/8272012/21782910/f7bae044-d669-11e6-9654-3561033afd53.png)

**Comment by And-re** [comment]
Ok, I know how to reproduce it:
1. write any chat message
2. go to settings (you will see empty nickname input)
3. open new chat input
4. you see your nickname there
