### ISSUE TITLE
Fix the text spacing issues in the respawn modal

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#193]
![screen shot 2017-01-09 at 12 40 38 pm](https://cloud.githubusercontent.com/assets/8272012/21782934/0efc9040-d66a-11e6-8be2-6fe0c7926c9b.png)

**Comment by And-re** [comment]
@michaeljcalkins I can quickly do this + fix that Enemy Player bug

**Comment by michaeljcalkins** [comment]
@And-re Go ahead and assign yourself, not sure with Enemy Player bug
