### ISSUE TITLE
Players get stuck in the top left corner

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#194]
![screen shot 2017-01-09 at 12 50 28 pm](https://cloud.githubusercontent.com/assets/8272012/21783023/640ca58e-d66a-11e6-877c-2a7af81fa145.png)

I think there is something wrong on their end, I have never experienced this.

**Comment by And-re** [comment]
@michaeljcalkins isn't this related to 
```javascript
// Allow Phaser to move the player
  // so that the map doesn't
  // kill them again.
  setTimeout(() => {
    store.dispatch(actions.player.setHealth(GameConsts.PLAYER_FULL_HEALTH))
  }, 100)
```
in onRespawnPlayer function?

**Comment by michaeljcalkins** [comment]
@And-re I don't see how that'd force them in the top left?

**Comment by And-re** [comment]
I think we are using (0,0) position by default
so maybe if a player tries to move left during that first 100ms it gets stuck

**Comment by michaeljcalkins** [comment]
I wonder if that player was actually a bot from something like google.

**Comment by And-re** [comment]
that's an interesting idea

**Comment by And-re** [comment]
@michaeljcalkins I finally found a way to reproduce this:
1. open 2 tabs of the same room
2. refresh one tab with the game and quickly go to another
3. you should see a player stuck in the top left corner
