### ISSUE TITLE
Damage stats don't display player's nickname

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#199]
![screen shot 2017-01-10 at 12 12 55 pm](https://cloud.githubusercontent.com/assets/8272012/21823258/28c51da6-d72f-11e6-8e89-764b1e7ccdfc.png)
![screen shot 2017-01-10 at 12 13 34 pm](https://cloud.githubusercontent.com/assets/8272012/21823260/2986e0a8-d72f-11e6-99b6-05e9450d45f1.png)

**Comment by And-re** [comment]
@michaeljcalkins it was fixed yesterday by me
