### ISSUE TITLE
Still having issues with players flying across the game when respawning

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#201]
This bug is happening because I put a 

<img src="https://cloud.githubusercontent.com/assets/8272012/21823893/e2d0d486-d731-11e6-94b9-9c251f679b36.jpg" height="200">

on the real issue which is players lack a state like the room has.

**Comment by michaeljcalkins** [comment]
@And-re I can close this if we remove tweening.  That's the only reason this happens.

**Comment by And-re** [comment]
@michaeljcalkins we can removed tweening, decrease player speed and maybe add some interpolation http://www.gabrielgambetta.com/fpm3.html
