### ISSUE TITLE
Refactor weapon changes into individual events

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#208]
- stop sending in every on move player event

**Comment by And-re** [comment]
@michaeljcalkins we may need to rethink our network communication:
![screen shot 2017-01-31 at 10 33 26](https://cloud.githubusercontent.com/assets/328414/22459437/e34fc82a-e7a0-11e6-987f-c003b825747f.png)
This seems to be an explanation for my problems with the network performance

**Comment by michaeljcalkins** [comment]
@And-re We'd have to be able to record dropped packets somehow.
I think we could make great strides by lowering the resolution a little bit still.

**Comment by And-re** [comment]
@michaeljcalkins If we somehow combine "move player", "weapon change" and "bullet fired" events we should be able to avoid that problem

**Comment by michaeljcalkins** [comment]
@And-re I think I see what you're saying. We would be moving towards one large yet minimal packet instead of many different packets that add up to the same size.

We still need to setup a test to confirm that this is an issue though.

**Comment by michaeljcalkins** [comment]
@And-re Is this necessary right now?  I feel like our system is working good as it is.

**Comment by And-re** [comment]
@michaeljcalkins no, but we may need to do something about "move_player" and "bullet_fired" events:  somehow merge them so we are not flooding the network
