### ISSUE TITLE
Was able to move when the round ended and the leaderboard modal was up

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#209]
![screen shot 2017-01-15 at 2 51 48 pm](https://cloud.githubusercontent.com/assets/8272012/21966943/3ac38306-db32-11e6-873a-dd6ac3468e53.png)
(that's me flying around in the background)

**Comment by michaeljcalkins** [comment]
I ran off the edge of the map and died changing my score.  Which means i could continue to kill people if they had been around me.

**Comment by And-re** [comment]
@michaeljcalkins no, you can't shoot or use jetpack when round ended and your moves aren't even sent to the server
still, we need to do something about possibility to change your score like that

**Comment by michaeljcalkins** [comment]
I think it's just not pausing the game and covering the window with the modal.  Happened again today.

**Comment by And-re** [comment]
ok, I think I found a way to fix this
