### ISSUE TITLE
Improve Leaderboards

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#214]
![image](https://cloud.githubusercontent.com/assets/328414/22259463/b33e52ae-e265-11e6-91eb-bce2b0b17c1c.png)

- [x] sorting
- [x] styling

**Comment by michaeljcalkins** [comment]
http://stackoverflow.com/a/37501595/1069899

```javascript
 firebase.database().ref('Regions').orderByChild("rank").on('child_added', function (regions) {
      loadRegions(regions.exportVal());
  });
```

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/363
