### ISSUE TITLE
Add more stats to Battle Stats

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#216]

**Comment by michaeljcalkins** [comment]
@And-re This could probably be an idea for a while until we have actionable items.

**Comment by And-re** [comment]
@michaeljcalkins I was talking about stats that are already available in firebase

**Comment by michaeljcalkins** [comment]
One I'd like to see is "Time In Game"

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/383
