### ISSUE TITLE
Redux action dispatch error

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#221]
The game crashed:
![screen shot 2017-01-26 at 13 07 41](https://cloud.githubusercontent.com/assets/328414/22330949/0a788a9e-e3c9-11e6-9df5-91c48462d395.png)

I think it's here:
```javascript
if (store.getState().player.jumpJetCounter < 0) {
      store.dispatch(actions.player.decrementJumpJetCounter(GameConsts.JUMP_JET_SPEED_REGENERATION))
    } else {
      store.dispatch(actions.player.setJumpJetCounter(0))
    }
```

**Comment by michaeljcalkins** [comment]
How did you get this to happen?
I don't think I've seen this bug.

**Comment by And-re** [comment]
@michaeljcalkins it just happened during the game and everything was freezed so I checked for the console errors

**Comment by michaeljcalkins** [comment]
@And-re I remember you mentioned something about this in our chat.  What was happening?

**Comment by And-re** [comment]
@michaeljcalkins I was playing 1v1 and using jetpack at that time

**Comment by michaeljcalkins** [comment]
I still haven't seen this one yet. @And-re Can we close for now?

**Comment by And-re** [comment]
I guess so. 2 weeks ago while I was doing another issue I changed some part of that code to stop unnecessary dispatch actions:
```js
} else if (store.getState().player.jumpJetCounter > 0) {
    store.dispatch(actions.player.setJumpJetCounter(0))
}
```
