### ISSUE TITLE
KeepCalm-Medium font not found

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#222]
![screen shot 2017-01-26 at 13 13 58](https://cloud.githubusercontent.com/assets/328414/22331121/04171ad4-e3ca-11e6-85a2-179f0e53a5e8.png)

**Comment by michaeljcalkins** [comment]
I say we switch to a font from https://fonts.google.com/ or a standard system font.
For whatever reason sometimes this font doesn't load and I don't know why but then people end up with a Times New Roman interface.

**Comment by michaeljcalkins** [comment]
@And-re Thoughts?

**Comment by And-re** [comment]
@michaeljcalkins I'm okay with a font from fonts.google.com

**Comment by michaeljcalkins** [comment]
<img width="833" alt="screen shot 2017-01-30 at 7 40 04 pm" src="https://cloud.githubusercontent.com/assets/8272012/22451508/f8a1e8ca-e723-11e6-920b-fe40933673ff.png">

**Comment by michaeljcalkins** [comment]
Waiting on this to make sure it works.
