### ISSUE TITLE
Unnecessary big phaser.map file requested > 331 KB

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#223]
![screen shot 2017-01-26 at 13 16 37](https://cloud.githubusercontent.com/assets/328414/22331159/365d0030-e3ca-11e6-8e96-2647581e8e1e.png)

**Comment by michaeljcalkins** [comment]
Would it be ok to remove the sourcemap file from the bottom of phaser?
https://rangersteve.io/js/phaser.min.js

![https___rangersteve_io_js_phaser_min_js_ _and_rangersteve_ _fix_user-doesnt-exist__origin_fix_user-doesnt-exist__1929_commits_](https://cloud.githubusercontent.com/assets/8272012/22336388/f15ea21e-e396-11e6-9854-0104f025006a.png)

**Comment by And-re** [comment]
@michaeljcalkins I don't think we need the sourcemap for production so it would be the best to have a way to control that via Webpack

**Comment by michaeljcalkins** [comment]
@And-re We could use the unminified version locally and use a minified, no sourcemap version for production.
