### ISSUE TITLE
Empty nicknames on Leaderboards page = undefined nickname on Battle Stats page

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#224]
![screen shot 2017-01-26 at 13 31 25](https://cloud.githubusercontent.com/assets/328414/22331446/c68b7118-e3cb-11e6-9ac2-741fb0e5d773.png)

https://rangersteve.io/battle-stats/undefined
![screen shot 2017-01-26 at 13 30 10](https://cloud.githubusercontent.com/assets/328414/22331411/94be736a-e3cb-11e6-99f1-e26ddca3820c.png)

**Comment by michaeljcalkins** [comment]
No one appears to actually have an empty username, I think there's a mismatch happening between username_lookup and users.

**Comment by michaeljcalkins** [comment]
![leaderboards_njk_-_rangersteve](https://cloud.githubusercontent.com/assets/8272012/22337087/f8bf3e04-e398-11e6-96be-de330104e847.png)

If you delete their uid from the leaderboards table they are removed.

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve/commit/3fdd319a1b3b7a5bfe85b9f2a9147e142983c77c
That will show you all of the undefined users on the leaderboard.
Hoping that my PR https://github.com/michaeljcalkins/rangersteve/pull/369 will fix this.

**Comment by And-re** [comment]
@michaeljcalkins it should fix this in the future cases but we have to do something about the current situation
e.g. we can manually assign them some random nicknames in firebase

**Comment by michaeljcalkins** [comment]
@And-re When we merge my fix their ids will be console.error'd and we can delete them from the leaderboard easily.

**Comment by And-re** [comment]
@michaeljcalkins There is no need to remove them.
The problem is that because they had empty nickname, they weren't added to the users and username_lookup collections
![screen shot 2017-01-26 at 23 39 03](https://cloud.githubusercontent.com/assets/328414/22353429/a5c69fca-e420-11e6-9277-436192e08828.png)

**Comment by And-re** [comment]
@michaeljcalkins Ok, I fixed this:
![screen shot 2017-01-26 at 23 47 24](https://cloud.githubusercontent.com/assets/328414/22353659/d6df1564-e421-11e6-9745-446bbf3b7c73.png)
![screen shot 2017-01-26 at 23 47 54](https://cloud.githubusercontent.com/assets/328414/22353668/e4442528-e421-11e6-8041-2c0c10d3ece9.png)

**Comment by michaeljcalkins** [comment]
@And-re Did you update the username_lookup and users?

**Comment by And-re** [comment]
@michaeljcalkins Tak

**Comment by michaeljcalkins** [comment]
@And-re Słodkie

**Comment by And-re** [comment]
@michaeljcalkins this empty player wasn't added to the username_lookup
![screen shot 2017-01-27 at 20 25 00](https://cloud.githubusercontent.com/assets/328414/22384440/b1b2684c-e4ce-11e6-85b0-85b6d922c7f2.png)

**Comment by michaeljcalkins** [comment]
@And-re Do you know how to do this? I thought it might just be a cache thing.

**Comment by And-re** [comment]
@michaeljcalkins No, I don't. Maybe something wrong with code related to username_lookup.

**Comment by michaeljcalkins** [comment]
I think this was related to our login being broken for sometime.  Going to close for now.
