### ISSUE TITLE
Firebase error while signing up with a Twitter account

### ISSUE THREAD

**Issue by And-re** [michaeljcalkins/rangersteve-ideas#225]
![screen shot 2017-01-26 at 13 39 30](https://cloud.githubusercontent.com/assets/328414/22331670/00f2687e-e3cd-11e6-8a61-dcf4591eb2f7.png)

**Comment by And-re** [comment]
It was tested on current production version but might be fixed by https://github.com/michaeljcalkins/rangersteve/pull/367

**Comment by michaeljcalkins** [comment]
It looks like you were signing in for the first time, this would be when it creates a new user record for you if it doesn't exist.

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/369
