### ISSUE TITLE
Add entity interpolation to moving players

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#226]
I don't know if tweening itself is performance heavy but we need some sort of interpolation.

**Comment by michaeljcalkins** [comment]
Don't worry about whether or not the player is dead I'll handle player visibility in https://github.com/michaeljcalkins/rangersteve-ideas/issues/227.  This is just for moving when in battle.

**Comment by And-re** [comment]
@michaeljcalkins ok, maybe something like https://github.com/gamestdio/timeframe will help

**Comment by michaeljcalkins** [comment]
@And-re Really all we need is to have the player "tween" to the latest position we received for them.
Like a tween but without the queuing and memory consumption.

- finishes before the next frame starts
- requires almost no memory (tween was awful)

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/381
