### ISSUE TITLE
NaN in the leaderboard modal

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#229]
![screen shot 2017-01-27 at 6 42 36 am](https://cloud.githubusercontent.com/assets/8272012/22374707/180cd29e-e45c-11e6-9fa8-41acadef4957.png)

**Comment by michaeljcalkins** [comment]
![screen shot 2017-01-27 at 2 01 37 pm](https://cloud.githubusercontent.com/assets/8272012/22390290/05e748fe-e49f-11e6-8f70-04ec4958e3f4.png)

**Comment by michaeljcalkins** [comment]
I bet you this is a divide by 0 issue.

**Comment by And-re** [comment]
@michaeljcalkins and I'm still not sure if the "Most accurate" stat is working properly. Sometimes I think I have around 30% of accuracy but still someone else with 8% of accuracy is there.

**Comment by And-re** [comment]
@michaeljcalkins this happens when e.g. bulletsFired = undefined

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/385

**Comment by And-re** [comment]
I just saw NaN for best kills per minute

**Comment by michaeljcalkins** [comment]
![screen shot 2017-02-04 at 10 41 29 am](https://cloud.githubusercontent.com/assets/8272012/22620761/8753c8ee-eac7-11e6-9597-bcf37c39016f.png)

**Comment by michaeljcalkins** [comment]
![screen shot 2017-02-03 at 12 38 11 pm](https://cloud.githubusercontent.com/assets/8272012/22620762/907f6e5a-eac7-11e6-9548-42e205192d3a.png)

**Comment by michaeljcalkins** [comment]
![screen shot 2017-02-03 at 11 15 27 am](https://cloud.githubusercontent.com/assets/8272012/22620764/971a8db2-eac7-11e6-851f-949bf37dc04c.png)

I think this tends to happen when someone new joins the game.

**Comment by And-re** [comment]
yes, someone with no stats

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/393
