### ISSUE TITLE
When using chat a 0 is prepended automatically to the message.

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#235]

**Comment by And-re** [comment]
@michaeljcalkins 0 appears when you go to Settings and open the chat input
Can you type "space" while at the end of round?

**Comment by michaeljcalkins** [comment]
1. I open the chat and type something in normally
2. Then open the settings modal and close
3. I open the chat and 0 is there

**Comment by And-re** [comment]
@michaeljcalkins this 0 is caused by Sound Effects Volume slider (if I remove it, there is no problem anymore)

**Comment by michaeljcalkins** [comment]
@And-re Did we merge anything to fix this?

**Comment by And-re** [comment]
@michaeljcalkins No, there is a serious issue with SettingsModal, HudChatHistory and the context of "this" when calling focus()

**Comment by michaeljcalkins** [comment]
@And-re I can tackle this next

**Comment by And-re** [comment]
@michaeljcalkins ok, so I can focus on the low quality mode task

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/411

**Comment by And-re** [comment]
This problem still exists
![screen shot 2017-02-19 at 09 26 14](https://cloud.githubusercontent.com/assets/328414/23100593/7d84635e-f685-11e6-94b6-d7d8c358b619.png)
