### ISSUE TITLE
Player had just appeared in the room and their player was visible, I then shot them and got a kill

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#236]

**Comment by michaeljcalkins** [comment]
1. they joined
2. their state was 1 during the loading stage
3. he was visible for me even though his game hadn't loaded fully
4. so i shot him before he could even move

**Comment by And-re** [comment]
@michaeljcalkins which PR is this? https://github.com/michaeljcalkins/rangersteve/pull/388 ?

**Comment by michaeljcalkins** [comment]
@And-re We are still having this issue. :/

**Comment by And-re** [comment]
@michaeljcalkins I have 3 ideas for this:
1. Improve map loading
2. Increase timeout in Boot state that's setting paused to false
3. Implement Spawn protection

**Comment by michaeljcalkins** [comment]
Waiting to see if this was fixed.

**Comment by And-re** [comment]
@michaeljcalkins I did the thing from the 2nd point. The first one might be useful as well.
