### ISSUE TITLE
Reduce max room size to six players and change room selection to _.sample instead of first one

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#237]
Eight players just feels like chaos
We often have 3 rooms where one has 6/8 players and the rest have 1/8
I want to see if this effects game performance

**Comment by michaeljcalkins** [comment]
@And-re Thoughts?  I want to see how these changes effect the game.

**Comment by michaeljcalkins** [comment]
We can limit this experiment to a week or two then switch it back.

**Comment by And-re** [comment]
@michaeljcalkins yes, we can set it to 6 players
