### ISSUE TITLE
Newly created remote players should start in a negative x and y of at least 500

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#240]
This will prevent new players from appearing in the corner for whatever reason.

**Comment by And-re** [comment]
@michaeljcalkins isn't there some kind of "alive" flag for Phaser objects that we can set to false by default?

**Comment by michaeljcalkins** [comment]
@And-re There is but this is still happening despite being at 0,0.

**Comment by And-re** [comment]
@michaeljcalkins but is it set to false?

**Comment by michaeljcalkins** [comment]
```
  newRemotePlayer.visible = false
  newRemotePlayer.anchor.setTo(GameConsts.PLAYER_ANCHOR)
  newRemotePlayer.alive = true
```

@And-re I'll try killing the player sprite on creation.

**Comment by And-re** [comment]
@michaeljcalkins you murderer!
