### ISSUE TITLE
Experiment with creating polygons using arcade slopes plugin 

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#241]
https://github.com/hexus/phaser-arcade-slopes/blob/master/src/ArcadeSlopes/TileSlopeFactory.js#L429

**Comment by michaeljcalkins** [comment]
We may be able to makeshift a function that creates custom polygons and then combine that with some sort of polygon decomposition map builder.

**Comment by michaeljcalkins** [comment]
https://phaser.io/examples/v2/box2d/polygon-decomposition

**Comment by And-re** [comment]
@michaeljcalkins here is a Tilesheet generator http://hexus.github.io/phaser-arcade-slopes/generator.html
Maybe there is a way to generate a tilesheet based on polygons.

**Comment by michaeljcalkins** [comment]
This will require extensive modifications to the slopes plugin.  You'd probably be better off writing a custom hook for polygons if you wanted them.

I tried changing polygons but I was getting really weird behavior.
