### ISSUE TITLE
Can't always shoot players when alive

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#249]
I play RS for a while and all of a sudden I can't shoot some of the players.  My bullets don't collide with their bodies.

**Comment by michaeljcalkins** [comment]
I have no idea what's causing this though.

**Comment by And-re** [comment]
I'm not sure as well

**Comment by michaeljcalkins** [comment]
This happens after they spawn and the spawn protection is gone.  It is likely due to the no damage buffer.

**Comment by michaeljcalkins** [comment]
It is definitely related to the new physics for the game.  The players don't appear to have bodys that collide with bullets.

Either the bullet or player is lacking a body.

**Comment by michaeljcalkins** [comment]
![screen shot 2017-03-07 at 9 13 09 am](https://cloud.githubusercontent.com/assets/8272012/23668637/978f6080-0316-11e7-92aa-ec0b4eb9b3bd.png)

**Comment by michaeljcalkins** [comment]
[9:13 AM] michaeljcalkins: The game isn't aware of the player!!
[9:14 AM] michaeljcalkins: I got reports and sometimes experienced where all players were invisible.
[9:14 AM] michaeljcalkins: We have a race condition where sometimes our game isn't updated with all the new players and thus you can't shoot them.
[9:15 AM] michaeljcalkins: We just need to refactor our on load event.

**Comment by michaeljcalkins** [comment]
![screen shot 2017-03-07 at 9 16 56 am](https://cloud.githubusercontent.com/assets/8272012/23668782/eb2bbc98-0316-11e7-86a7-35b2a0437b37.png)

**Comment by michaeljcalkins** [comment]
Was reproducible when we added a bunch of players to the game.
All players are not correctly loaded when people join the game.
