### ISSUE TITLE
Gamemode: Gun Game

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#258]
Start with ak47
Get a kill, you get the next weapon
Die and you go back a weapon
Kill with the last hardest gun and you win

----

Start guns that are easy to get kills with and progress towards guns that are hard to get kills with.

**Comment by And-re** [comment]
@michaeljcalkins last hardest or least hardest?

**Comment by michaeljcalkins** [comment]
@And-re Last gun is hardest to get a kill with (likely deagle or sniper)

**Comment by And-re** [comment]
@michaeljcalkins yes, I think right now deagle might be the hardest 
but you said: "Start with deagle"
so I thought you wanted it to be easier and easier

**Comment by michaeljcalkins** [comment]
@And-re My bad! Updated the description.
