### ISSUE TITLE
Redesign homepage to feel more like a game

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#261]
- Convert front facing site
- Home | Weapons | Map Editor | Store | Updates | Settings
- Video for homepage background

**Comment by michaeljcalkins** [comment]
http://files.gamebanana.com/img/ss/gamefiles/57b0dd818ba6a.jpg

**Comment by michaeljcalkins** [comment]
https://gamefaqs.akamaized.net/screens/7/a/a/gfs_496032_1_1.jpg

**Comment by michaeljcalkins** [comment]
@And-re We can easily keep the style changes you made but the added complexity to make it SEO worth for mostly static content is going to be too much trouble.

**Comment by michaeljcalkins** [comment]
![rangerstevehome](https://cloud.githubusercontent.com/assets/8272012/23869525/799c3be2-07e0-11e7-9dd1-3e372f27d7cf.png)

**Comment by michaeljcalkins** [comment]
After experimenting with layouts I think the Overwatch layout is by far the best one still.

**Comment by And-re** [comment]
what about this header?
https://cdn.discordapp.com/attachments/232591848626061313/283733185332772864/Screen_Shot_2017-02-21_at_23.54.16.png

**Comment by michaeljcalkins** [comment]
@And-re I like what you did with it.  Replace "Home" with "Ranger Steve" and I think it'll be good.

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/430
