### ISSUE TITLE
Replace the bullet fired event by using `shooting: true` in the move player event

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#264]
If a player's `shooting` var is `true` then they should be shooting bullets

**Comment by michaeljcalkins** [comment]
@And-re You mind taking this one on and I'll start building gamemodes?

**Comment by And-re** [comment]
@michaeljcalkins ok

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/439
