### ISSUE TITLE
Server needs to determine damage somehow, getting killed due to a slow player's client

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#266]
![screen shot 2017-02-25 at 12 22 11 pm](https://cloud.githubusercontent.com/assets/8272012/23334503/2a129266-fb55-11e6-94b1-b83ba6e524e3.png)

No one around me and I get killed

**Comment by michaeljcalkins** [comment]
![screen shot 2017-02-25 at 12 25 42 pm](https://cloud.githubusercontent.com/assets/8272012/23334520/934b5c0e-fb55-11e6-90ea-91603d1610e1.png)
no bullets on screen

**Comment by michaeljcalkins** [comment]
@And-re I have no idea how we'll accomplish this one, I'm open to any ideas though.

**Comment by And-re** [comment]
@michaeljcalkins without server-side collisions - I'm not sure as well

**Comment by michaeljcalkins** [comment]
Just going to wait on this.
