### ISSUE TITLE
Player frozen and not moving, assuming disconnected and not removed

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#267]
![screen shot 2017-02-27 at 11 54 24 am](https://cloud.githubusercontent.com/assets/8272012/23377156/b63af000-fce3-11e6-9145-08ac2ca0133d.png)

**Comment by michaeljcalkins** [comment]
![screen shot 2017-02-27 at 4 14 44 pm](https://cloud.githubusercontent.com/assets/8272012/23385898/e6c1bc8a-fd07-11e6-9a00-4af8b3adfe12.png)

**Comment by michaeljcalkins** [comment]
![screen shot 2017-03-07 at 12 41 28 pm](https://cloud.githubusercontent.com/assets/8272012/23677529/59b1a25e-0335-11e7-9ca5-bd4acf9ff665.png)

In this case Jormor just had really bad ping, 400 to 1000.

**Comment by michaeljcalkins** [comment]
@And-re Is there a chance you can take a look at this?  My last big PR was supposed to be an attempt at this but it doesn't seem to have worked and I'm not sure where to go from there.

**Comment by And-re** [comment]
@michaeljcalkins I can take a look when I have some free time

**Comment by michaeljcalkins** [comment]
When servers were restarted players were still in the room even though they had been disconnected.

**Comment by michaeljcalkins** [comment]
![screen shot 2017-03-20 at 9 57 28 am](https://cloud.githubusercontent.com/assets/8272012/24111473/b79a74e0-0d53-11e7-9238-da228740301d.png)
I have no idea how to reproduce this bug.

**Comment by michaeljcalkins** [comment]
I was sort of able to replicate this issue when I had two tabs in the same window.  One was active and one was inactive.

**Comment by And-re** [comment]
I've also reproduced that by accident locally when I had 3 tabs and was kicked for inactivity in one of them

**Comment by And-re** [comment]
@michaeljcalkins I finally managed to reproduce that locally.
If you don't have the "auto respawn" feature enabled you still respawn for remote players but they can't kill you.

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/447
