### ISSUE TITLE
Move all assets to cloudfront so game server isn't serving them

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#271]

**Comment by michaeljcalkins** [comment]
@And-re I have set this up but then realized if we move to have game servers on Digital Ocean this won't be necessary at first.

**Comment by And-re** [comment]
@michaeljcalkins we may test it now to see if it makes any difference for players

**Comment by michaeljcalkins** [comment]
@And-re The other cool thing is that in order to deploy new client side code or images we just replace it in S3 and destroy the cache for cloudfront.
http://d3banvqa7actu5.cloudfront.net/js/app.js

**Comment by And-re** [comment]
@michaeljcalkins so do you want to test it? we can compare metrics to see if it helps somehow

**Comment by michaeljcalkins** [comment]
Yeah I'll make a new PR for it after I make sure Phaser plays with cross
domain loading nicely.

**Comment by And-re** [comment]
do you mean using something like this:
```js
function preload() {

    game.stage.backgroundColor = '#85b5e1';

    game.load.baseURL = 'http://examples.phaser.io/assets/';
    game.load.crossOrigin = 'anonymous';

    game.load.image('player', 'sprites/phaser-dude.png');
    game.load.image('platform', 'sprites/platform.png');

}
```
