### ISSUE TITLE
When a player is shot who doesn't exist in a room emit a player left event until removed from all player's view

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#277]

**Comment by michaeljcalkins** [comment]
These players are specifically ones who can't be killed when shot.  The idle detection does a good job with the rest.

**Comment by And-re** [comment]
I think there is just a missing player_left event somewhere and it's related to https://github.com/michaeljcalkins/rangersteve-ideas/issues/267

**Comment by michaeljcalkins** [comment]
@And-re I don't think this is actually a bug I think you fixed it in your auto respawn thing.
