### ISSUE TITLE
Gamemode: Tag

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#284]
Tag

3 teams
When you die you join that team
When there is only one team left they win

**Comment by And-re** [comment]
@michaeljcalkins I'm not sure about this gamemode: I don't like it in diep.io and we would need to reimplement many things because we only support 2 teams right now

**Comment by michaeljcalkins** [comment]
@And-re I'm going to save the hard to make ones (like this) for last.  I really enjoy the diep.io version and when I play it in Airsoft.  

We're probably going to have a couple that we don't like a whole lot but are favorites for other people.
