### ISSUE TITLE
Add a level system based on the amount of score the player has earned from rounds

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#292]
![screen shot 2017-03-28 at 10 31 11 am](https://cloud.githubusercontent.com/assets/8272012/24418698/b13deff6-13a1-11e7-8adf-5c7880fa7106.png)
![screen shot 2017-03-28 at 10 31 00 am](https://cloud.githubusercontent.com/assets/8272012/24418701/b331dc00-13a1-11e7-82e5-7b1aa4c94d81.png)

**Comment by michaeljcalkins** [comment]
We should literally copy Rocket League in this regard as much as possible.

**Comment by And-re** [comment]
@michaeljcalkins every rank except for Rocketeer?
Something like this?
Rookie: 0-999
Semi-pro: 1 000-4 999
Pro: 5 000-9 999
Veteran: 10 000-49 999
Expert: 50 000-99 999
Master: 100 000-499 999
Legend: 500 000-

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/450
