### ISSUE TITLE
When a window is resized larger than it started tilemap tiles disappear

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#37]
![screen shot 2016-09-21 at 8 13 34 am](https://cloud.githubusercontent.com/assets/8272012/18716937/63bccde0-7fd3-11e6-988d-bbb113203741.png)

**Comment by michaeljcalkins** [comment]
`moment.tz.setDefault('America/Los_Angeles')` is set in the server and client

**Comment by michaeljcalkins** [comment]
Waiting to see if this fixed it

**Comment by michaeljcalkins** [comment]
https://github.com/photonstorm/phaser/pull/2691

**Comment by michaeljcalkins** [comment]
https://github.com/photonstorm/phaser/issues/2646

**Comment by michaeljcalkins** [comment]
https://github.com/michaeljcalkins/rangersteve-ideas/issues/41

**Comment by michaeljcalkins** [comment]
Lol I have no idea...

**Comment by michaeljcalkins** [comment]
![screen shot 2016-10-26 at 7 35 35 pm](https://cloud.githubusercontent.com/assets/8272012/19752579/65141c92-9bb3-11e6-9713-d10614e4813d.png)

**Comment by daniphilia** [comment]
Reaching out to them would be the optimal course of action; give it 2-3 days, I guess.
