### ISSUE TITLE
Can't type any key that is bound in the chat sometimes.

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#74]

**Comment by And-re** [comment]
not only 'r', other mapped keys as well (e.g. spacebar)

**Comment by michaeljcalkins** [comment]
When the chat opens:

1. Disable game input
2. Reset game input, 
3. Let player type and send their message 
4. Enable game input
5. Rebind game input keys

**Comment by michaeljcalkins** [comment]
When the round ends stop all sound effects and reset inputs.
