### ISSUE TITLE
IDEA: Health packages and powerups dispersed across the map

### ISSUE THREAD

**Issue by daniphilia** [michaeljcalkins/rangersteve-ideas#79]
Random spawns of health and powerups.

**Comment by michaeljcalkins** [comment]
@daniphilia 

Like, "OH IM BEING CHASED OH MY GOD MY HEALTH ONE MORE HIT AND IM SURELY DONE" 
- health pack spawns right on top of you
AHHHHHHHHH
- crazy OP counterplay
- enemy is ded

**Comment by michaeljcalkins** [comment]
I envision this coming after gamemodes and character classes are done.

**Comment by michaeljcalkins** [comment]
I have mixed feelings about this, the healing system handles this pretty well atm.  Would likely require a play test.

**Comment by michaeljcalkins** [comment]
We can revisit this someday if we get more requests but I'm gonna vote no for now.

**Comment by And-re** [comment]
Exactly, we can add it later.
