### ISSUE TITLE
Kill log, chat, kill streaks, and scoreboard cannot block mouse clicks on canvas.

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#85]
Can't shoot when mouse is on them

**Comment by And-re** [comment]
There maybe some way to pass the events through all of them so there won't be a need to make them canvas based

**Comment by michaeljcalkins** [comment]
I have lost several kills and then was killed over this, may need to be pushed to alpha.

**Comment by michaeljcalkins** [comment]
Attempt to have clicks go through the ui into canvas.  
@And-re any links to resources would be helpful

**Comment by michaeljcalkins** [comment]
@And-re Idk what's involved or what to look for but @daniphilia might be interested in completing this one.

**Comment by And-re** [comment]
I found this: http://stackoverflow.com/questions/1009753/pass-mouse-events-through-absolutely-positioned-element

**Comment by michaeljcalkins** [comment]
Just confirmed that this works by adding it to hud elements.  Elements might need `display: block` or something.
