### ISSUE TITLE
Integrate firebase auth system

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#9]

**Comment by andrewdelprete** [comment]
Why Firebase?

**Comment by michaeljcalkins** [comment]
I get a realtime auth system for free that has social logins built in.

https://www.firebase.com/docs/web/guide/user-auth.html#section-providers

![screen shot 2016-09-20 at 2 32 27 pm](https://cloud.githubusercontent.com/assets/8272012/18689655/211f3b88-7f3f-11e6-9919-0c062bb7134e.png)
