### ISSUE TITLE
Places to post RangerSteve.io

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#90]
- https://www.reddit.com/r/playmygame/
- https://news.ycombinator.com/
- http://www.html5gamedevs.com/topic/22657-phaser-rangersteveio-ranger-steve-buffalo-invasion/
- https://www.reddit.com/r/IoGames/
- https://github.com/leereilly/games
- https://www.patreon.com
- https://docs.google.com/forms/d/e/1FAIpQLSeLVUTddZTI83qQNR0biZ5teXNSxkr9u5CPds61oxWzHcTXkA/viewform
- http://us3.campaign-archive1.com/?u=4ad274b490aa6da8c2d29b775&id=eb208d2600&e=949688834b

**Comment by michaeljcalkins** [comment]
http://gamedev.stackexchange.com/questions/2285/where-to-promote-your-indie-game

**Comment by michaeljcalkins** [comment]
http://gamedev.stackexchange.com/questions/1639/how-can-i-promote-my-game

**Comment by michaeljcalkins** [comment]
Make a map based on music from Pixel networks or something that pulls in their music.

**Comment by michaeljcalkins** [comment]
https://www.youtube.com/channel/UCYfybUu1hUKRZl3r7FYAgHg

**Comment by michaeljcalkins** [comment]
http://iogames.space/

**Comment by michaeljcalkins** [comment]
https://www.reddit.com/r/IoGames/

**Comment by michaeljcalkins** [comment]
Play diep.io and get to the top with your nickname as `RangerSteve.io`.

**Comment by itsshady101** [comment]
https://itch.io/ <-- itch is probably biggest indie gaming community and many many big youtubers like pewdiepie pick up games for their videos from there

**Comment by michaeljcalkins** [comment]
Steam as a F2P game.

**Comment by michaeljcalkins** [comment]
https://help.twitch.tv/customer/en/portal/articles/2348988-adding-a-game-and-box-art-to-the-directory

**Comment by michaeljcalkins** [comment]
http://www.themeatly.com/submit-your-game/

**Comment by michaeljcalkins** [comment]
http://gamejolt.com/

**Comment by michaeljcalkins** [comment]
https://www.youtube.com/channel/UChUVdBih4m5GoKi-wd8pMiA

**Comment by And-re** [comment]
@michaeljcalkins isn't this youtube channel only for strategy games?

**Comment by michaeljcalkins** [comment]
http://game.wtf/

**Comment by michaeljcalkins** [comment]
Work on getting a vice article

**Comment by michaeljcalkins** [comment]
Eric Barnes article he started writing months ago

**Comment by michaeljcalkins** [comment]
Email Richard from Phaser.io about doing a blog article.

**Comment by michaeljcalkins** [comment]
Get our arcade polygons plugin launched and put a post on the HTML5 game devs forum with lots of links back to our game using examples.

**Comment by michaeljcalkins** [comment]
https://help.twitch.tv/customer/en/portal/articles/2348988-adding-a-game-and-box-art-to-the-directory

**Comment by michaeljcalkins** [comment]
http://www.pcgamer.com/free-games-of-the-week/

**Comment by michaeljcalkins** [comment]
http://www.kongregate.com/

**Comment by michaeljcalkins** [comment]
http://www.newgrounds.com/

**Comment by michaeljcalkins** [comment]
Find YouTubers who play shooter games or aggressive 2d shooter games.

**Comment by michaeljcalkins** [comment]
https://www.youtube.com/channel/UC-LlzSIFZjvmhwOm4SKQQHA/about

**Comment by michaeljcalkins** [comment]
https://www.youtube.com/channel/UCy6xGaMhm74YeHMDGgEr7kg

**Comment by michaeljcalkins** [comment]
http://vseigru.net/
https://www.crazygames.com/

**Comment by michaeljcalkins** [comment]
https://thenextweb.com/contributors/moomoo-io-great-io-game/#.tnw_GF85lVsI

**Comment by michaeljcalkins** [comment]
Start contacting companies that want to show off their tech by using RangerSteve.io as an example of the types of games you can play online.
