### ISSUE TITLE
Players slide too much when just walking, turn up the the friction a little bit

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#92]
From Hermier

**Comment by michaeljcalkins** [comment]
@And-re Do you think this is valid?

**Comment by And-re** [comment]
We can try to do it (maybe using DAT.gui) and see how it feels.
This is a bigger problem:
![screen shot 2016-10-25 at 00 02 04](https://cloud.githubusercontent.com/assets/328414/19665715/a5b0c142-9a46-11e6-9172-4a0f2b2acf9c.png)
You can see the stairs but they behave like slopes.

**Comment by michaeljcalkins** [comment]
I got frustrated with the steps ruining playability and that map is just one big image instead of a tilemap.  So that was the fastest way to make it a ramp without editing the giant image my computer can barely handle.

**Comment by And-re** [comment]
I think we shouldn't stop the walking animation while we are still moving left or right.
